language = "Typescript"

[redpanda_config]
broker = "localhost:19092"
message_timeout_ms = 1000
retention_ms = 30000
replication_factor = 1

[clickhouse_config]
db_name = "local"
user = "panda"
password = "pandapass"
use_ssl = false
host = "localhost"
host_port = 18123
native_port = 9000

[http_server_config]
host = "localhost"
port = 4410
management_port = 5411
proxy_port = 4411

[redis_config]
key_prefix = "MSLITE"
hostname = "127.0.0.1"
# The Redis port has been intentionally changed from the default 6379 to 6740.
port = 6740
tls = false

[git_config]
main_branch_name = "main"

[temporal_config]
db_user = "temporal"
db_password = "temporal"
db_port = 5433
temporal_port = 7233
temporal_version = "1.22.3"
admin_tools_version = "1.22.3"
ui_version = "2.21.3"
ui_port = 8080
ui_cors_origins = "http://localhost:3000"
config_path = "config/dynamicconfig/development-sql.yaml"
postgresql_version = "13"

[supported_old_versions]

[features]
streaming_engine = true
workflows = false
data_model_v2 = true
olap = true
ddl_plan = false

[typescript_config]
package_manager = "pnpm"

[authentication]
admin_api_key = "199d13d8201f7418054de884f3a955c928122ab3"
